export const actionType = {
    GET_MOVIES: "GET_MOVIES",
    GET_MOVIE_DETAIL: "GET_MOVIE_DETAIL",
    GET_TRENDING_MOVIES: "GET_TRENDING_MOVIES",
    SEARCH_MOVIE: "SEARCH_MOVIE",
    GET_POPULAR_TV: "GET_POPULAR_TV"

}