export const actionType = {
    GET_MOVIES: "GET_MOVIES", 
    GET_MORE_MOVIES: "GET_MORE_MOVIES", 
    GET_TRENDING_MOVIES: "GET_TRENDING_MOVIES",
    GET_NOWPLAYING_MOVIES: "GET_NOWPLAYING_MOVIES",
    GET_UPCOMING_MOVIES: "GET_UPCOMING_MOVIES",
    GET_MOVIE_DETAIL: "GET_MOVIE_DETAIL",
    SEARCH_MOVIE: "SEARCH_MOVIE",
    GET_POPULAR_TV: "GET_POPULAR_TV",
    GET_TV_DETAIL: "GET_TV_DETAIL",
    GET_TOPRATED_MOVIES: "GET_TOPRATED_MOVIES",
    
}